package taskmanagement.commands.enums;

public enum CommandType
{
    CREATENEWPERSON,
    SHOWALLPEOPLE,
    SHOWPERSONACTIVITY,
    CREATENEWTEAM,
    CREATEBOARD,
    SHOWALLTEAMS,
    ADDPERSONTOTEAM,
    SHOWALLTEAMMEMBERS,
    SHOWBOARDACTIVITY,
    CREATENEWBUG,
    CREATENEWSTORY,
    CREATENEWFEEDBACK,
    CHANGEBUGSTATUS,
    CHANGEBUGSEVERITY,
    CHANGEBUGPRIORITY,
    CHANGESTORYSTATUS,
    CHANGESTORYSIZE,
    CHANGESTORYPRIORITY,
    CHANGEFEEDBACKSTATUS,
    CHANGEFEEDBACKRATING,
    ASSIGNTASKTOPERSON,
    UNASSIGNTASKTOPERSON,
    ADDCOMMENTTOTASK,
    LISTALLTASKS,
    LISTBUGS,
    LISTSTORIES,
    LISTFEEDBACKS,
    LISTTASKWITHASSIGNEE
}
